name: Makefile CI
run-name: "Makefile CI ${{ inputs.leg || github.event_name }} ${{ inputs.racecar_run }}"

on:
  workflow_dispatch:
    inputs:
      leg:
        description: "baseline (uninstrumented) or instrumented (under chalk/curiosity)"
        type: choice
        options: [instrumented, baseline]
        default: baseline
      profile:
        description: "CrashOverride chalk profile"
        type: string
        default: curiosity-tests-racecar
      racecar_run:
        description: "racecar correlation token, echoed into the run name"
        type: string
        default: ""
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]


env:
  CHALK_ON: ${{ inputs.leg == 'instrumented' }}
jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: dmcoles/amiga-evo-cicd
      credentials:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
    steps: 
      - uses: actions/checkout@v4
      - name: run build
        run: |
           vamos -c /usr/amiga/.vamosrc --cwd esource: -V system:/usr/amiga -V esource:$GITHUB_WORKSPACE make build=release
           vamos -c /usr/amiga/.vamosrc --cwd esource:axSetupTool -V system:/usr/amiga -V esource:$GITHUB_WORKSPACE make build=release
           vamos -c /usr/amiga/.vamosrc --cwd esource:axUserEditor -V system:/usr/amiga -V esource:$GITHUB_WORKSPACE make build=release           

      - name: add build artifacts to publish
        run: |
          apk add lha
          mkdir downloads
          mkdir downloads/utils
          cp $GITHUB_WORKSPACE/express5 downloads
          cp $GITHUB_WORKSPACE/ACP downloads
          cp $GITHUB_WORKSPACE/jsonImport downloads/utils
          cp $GITHUB_WORKSPACE/icon2cfg downloads/utils
          cp $GITHUB_WORKSPACE/qwk downloads/utils
          cp $GITHUB_WORKSPACE/ftn downloads/utils
          cp $GITHUB_WORKSPACE/axSetupTool/axSetupTool downloads/utils 
          cp $GITHUB_WORKSPACE/axUserEditor/axUserEditor downloads/utils 
          cd downloads
          lha a ../amiExpress-nightly${{ github.sha }}.lha *
          ls ../

      - name: Get current date
        id: date
        run: |
          echo "builddate={$(date +'%Y-%m-%d')}" >> $GITHUB_OUTPUT
          
      - name: Update release files and title
        uses: mini-bomba/create-github-release@v1.2.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: dev-build
          name: automated dev build ${{ steps.date.outputs.builddate }}
          files: amiExpress-nightly${{ github.sha }}.lha
